import { Agent, Benchmark, Run, LeaderboardEntry, Trace, TraceMessage } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'GPT-4 Agent',
    provider: 'OpenAI',
    endpoint: 'https://api.openai.com/v1/chat/completions',
    authType: 'bearer',
    headers: { 'Content-Type': 'application/json' },
    createdAt: new Date('2024-10-15'),
    status: 'active',
  },
  {
    id: 'agent-2',
    name: 'Claude Sonnet Agent',
    provider: 'Anthropic',
    endpoint: 'https://api.anthropic.com/v1/messages',
    authType: 'apikey',
    createdAt: new Date('2024-10-18'),
    status: 'active',
  },
  {
    id: 'agent-3',
    name: 'Custom Agent v2',
    provider: 'Custom',
    endpoint: 'https://api.example.com/agent',
    authType: 'bearer',
    createdAt: new Date('2024-11-01'),
    status: 'active',
  },
  {
    id: 'agent-4',
    name: 'Gemini Agent',
    provider: 'Google',
    endpoint: 'https://api.google.com/gemini',
    authType: 'apikey',
    createdAt: new Date('2024-11-05'),
    status: 'inactive',
  },
];

export const mockBenchmarks: Benchmark[] = [
  {
    id: 'bench-1',
    name: 'Customer Support Benchmark',
    description: 'Avalia a capacidade de agentes em lidar com cenários de atendimento ao cliente',
    domain: 'Customer Support',
    tasksCount: 25,
    tasks: [
      {
        id: 'task-1',
        prompt: 'Um cliente reporta que não consegue fazer login na conta',
        expectedTool: 'reset_password',
        constraints: ['Não deve solicitar informações sensíveis diretamente'],
        maxTurns: 5,
      },
      {
        id: 'task-2',
        prompt: 'Cliente solicita reembolso de produto defeituoso',
        expectedTool: 'process_refund',
        maxTurns: 4,
      },
    ],
    createdAt: new Date('2024-10-20'),
  },
  {
    id: 'bench-2',
    name: 'Code Generation Tasks',
    description: 'Testa habilidades de geração e análise de código',
    domain: 'Software Engineering',
    tasksCount: 40,
    tasks: [
      {
        id: 'task-3',
        prompt: 'Criar uma função Python para validar emails',
        constraints: ['Deve usar regex', 'Incluir testes unitários'],
        maxTurns: 3,
      },
    ],
    createdAt: new Date('2024-10-25'),
  },
  {
    id: 'bench-3',
    name: 'Data Analysis Scenarios',
    description: 'Cenários de análise e processamento de dados',
    domain: 'Data Science',
    tasksCount: 30,
    tasks: [],
    createdAt: new Date('2024-11-01'),
  },
];

export const mockRuns: Run[] = [
  {
    id: 'run-1',
    benchmarkId: 'bench-1',
    benchmarkName: 'Customer Support Benchmark',
    agentId: 'agent-1',
    agentName: 'GPT-4 Agent',
    status: 'completed',
    startedAt: new Date('2024-11-09T10:30:00'),
    completedAt: new Date('2024-11-09T11:15:00'),
    progress: 100,
    successRate: 92,
    toolCorrectness: 88,
    violations: 2,
    avgTurns: 3.2,
    totalCost: 2.45,
    avgLatency: 1.8,
  },
  {
    id: 'run-2',
    benchmarkId: 'bench-1',
    benchmarkName: 'Customer Support Benchmark',
    agentId: 'agent-2',
    agentName: 'Claude Sonnet Agent',
    status: 'completed',
    startedAt: new Date('2024-11-09T14:00:00'),
    completedAt: new Date('2024-11-09T14:50:00'),
    progress: 100,
    successRate: 88,
    toolCorrectness: 92,
    violations: 1,
    avgTurns: 3.8,
    totalCost: 1.89,
    avgLatency: 1.5,
  },
  {
    id: 'run-3',
    benchmarkId: 'bench-2',
    benchmarkName: 'Code Generation Tasks',
    agentId: 'agent-1',
    agentName: 'GPT-4 Agent',
    status: 'running',
    startedAt: new Date('2024-11-10T09:00:00'),
    progress: 65,
    avgTurns: 2.5,
    totalCost: 3.12,
    avgLatency: 2.1,
  },
  {
    id: 'run-4',
    benchmarkId: 'bench-2',
    benchmarkName: 'Code Generation Tasks',
    agentId: 'agent-3',
    agentName: 'Custom Agent v2',
    status: 'pending',
    startedAt: new Date('2024-11-10T09:30:00'),
    progress: 0,
  },
  {
    id: 'run-5',
    benchmarkId: 'bench-3',
    benchmarkName: 'Data Analysis Scenarios',
    agentId: 'agent-2',
    agentName: 'Claude Sonnet Agent',
    status: 'failed',
    startedAt: new Date('2024-11-09T16:00:00'),
    completedAt: new Date('2024-11-09T16:05:00'),
    progress: 15,
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    agentId: 'agent-1',
    agentName: 'GPT-4 Agent',
    successRate: 92,
    toolCorrectness: 88,
    violations: 2,
    avgTurns: 3.2,
    totalCost: 2.45,
    avgLatency: 1.8,
    benchmarkId: 'bench-1',
  },
  {
    rank: 2,
    agentId: 'agent-2',
    agentName: 'Claude Sonnet Agent',
    successRate: 88,
    toolCorrectness: 92,
    violations: 1,
    avgTurns: 3.8,
    totalCost: 1.89,
    avgLatency: 1.5,
    benchmarkId: 'bench-1',
  },
  {
    rank: 3,
    agentId: 'agent-3',
    agentName: 'Custom Agent v2',
    successRate: 85,
    toolCorrectness: 82,
    violations: 4,
    avgTurns: 4.1,
    totalCost: 1.95,
    avgLatency: 2.2,
    benchmarkId: 'bench-1',
  },
];

const sampleMessages: TraceMessage[] = [
  {
    id: 'msg-1',
    type: 'user',
    content: 'Um cliente reporta que não consegue fazer login na conta',
    timestamp: new Date('2024-11-09T10:30:00'),
  },
  {
    id: 'msg-2',
    type: 'agent',
    content: 'Entendo o problema. Vou verificar a conta do cliente e auxiliar no processo de reset de senha.',
    timestamp: new Date('2024-11-09T10:30:02'),
  },
  {
    id: 'msg-3',
    type: 'tool',
    content: 'Verificando dados da conta do usuário',
    timestamp: new Date('2024-11-09T10:30:03'),
    toolName: 'check_user_account',
    parameters: { userId: 'user123' },
    result: { accountExists: true, locked: false, lastLogin: '2024-11-01' },
  },
  {
    id: 'msg-4',
    type: 'agent',
    content: 'A conta está ativa. Vou iniciar o processo de reset de senha.',
    timestamp: new Date('2024-11-09T10:30:05'),
  },
  {
    id: 'msg-5',
    type: 'tool',
    content: 'Enviando email de reset de senha',
    timestamp: new Date('2024-11-09T10:30:06'),
    toolName: 'reset_password',
    parameters: { userId: 'user123', email: 'customer@example.com' },
    result: { success: true, emailSent: true },
  },
  {
    id: 'msg-6',
    type: 'agent',
    content: 'Email de reset de senha enviado com sucesso. O cliente deve receber as instruções em alguns minutos.',
    timestamp: new Date('2024-11-09T10:30:08'),
  },
];

export const mockTraces: Trace[] = [
  {
    id: 'trace-1',
    runId: 'run-1',
    taskId: 'task-1',
    taskName: 'Login Issue Resolution',
    messages: sampleMessages,
    success: true,
    turns: 3,
    cost: 0.12,
    latency: 1.8,
  },
  {
    id: 'trace-2',
    runId: 'run-1',
    taskId: 'task-2',
    taskName: 'Refund Processing',
    messages: sampleMessages.slice(0, 4),
    success: true,
    turns: 2,
    cost: 0.09,
    latency: 1.5,
  },
];
